In [2]:
%load_ext autoreload
%autoreload 2
import mido
import numpy as np
from itertools import combinations

from music_tools.midi_frame import MidiFrame
import music_tools.scales as scales
import music_tools.midi_utils as mu
from music_tools.chords import ChordSuggester

In [3]:

m = mido.MidiFile(filename="MIDI_Files/vivconct.mid")
mf = MidiFrame(m, info_type="dispatched")
mf.make_playing_track_frame([i for i in range(16)])

notes = mu.to_chroma(mf.playing_track_frame.get_sub_dataframe(0, 10).note.to_numpy())

scale = scales.suggest_scales(notes)[0]
scale = scale[0].scale_in(scale[1])
print(scale)
print(mu.CHROMA_NAMES[scale.chromas])
print("======================")

nb_note = 3
nb_chord = 5 # not a problem if more than nb of combinations
sug = ChordSuggester(nb_note, scale, notes)
chords = sug.suggest_chords(nb_chord)
print(chords)
print(mu.CHROMA_NAMES[sug.suggest_chords(nb_chord)])

Lydian Scale in F
['F' 'G' 'A' 'B' 'C' 'D' 'E']
[[ 9  0  4]
 [ 9  2  4]
 [ 9 11  4]
 [ 5  9  4]
 [ 7  9  4]]
[['A' 'C' 'E']
 ['A' 'D' 'E']
 ['A' 'B' 'E']
 ['F' 'A' 'E']
 ['G' 'A' 'E']]


c:\Users\anony\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
