In [136]:
%load_ext autoreload
%autoreload 2
import mido
import numpy as np
from itertools import combinations

from music_tools.midi_frame import MidiFrame
import music_tools.scales as scales
import music_tools.midi_utils as mu
from music_tools.chords import ChordSuggester

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [143]:

m = mido.MidiFile(filename="MIDI_Files/vivconct.mid")
mf = MidiFrame(m, info_type="dispatched")
mf.make_playing_track_frame([i for i in range(16)])

music_dataframe = mf.playing_track_frame.get_sub_dataframe(0, 10)

scale = scales.suggest_scales(mu.to_chroma(music_dataframe.note.to_numpy()))[0]
scale = scale[0].scale_in(scale[1])
print(scale)
print(mu.CHROMA_NAMES[scale.chromas])
print("======================")

note_count = 3
chord_count = 5 # not a problem if more than nb of combinations
sug = ChordSuggester(scale, music_dataframe, note_count=note_count)
chords = sug.suggest_chords(chord_count)
print(chords)
print(mu.CHROMA_NAMES[sug.suggest_chords(chord_count)])

Lydian Scale in F
['F' 'G' 'A' 'B' 'C' 'D' 'E']
[[ 9  0  4]
 [ 9  2  4]
 [ 9 11  4]
 [ 5  9  4]
 [ 7  9  4]]
[['A' 'C' 'E']
 ['A' 'D' 'E']
 ['A' 'B' 'E']
 ['F' 'A' 'E']
 ['G' 'A' 'E']]


In [109]:
0.3472222222222222

array([27, 12,  9, 18, 27])